from .contracts import (
    AttendanceRecordDTO,
    AttendanceRepositoryContract,
    AttendanceUpdateDTO,
    BackupDownload,
    BackupProvider,
    DatabaseCompatibilityError,
    MemberDTO,
    SyncOperationDTO,
    SyncResultDTO,
    TrainingSessionDTO,
    UnitOfWorkContract,
    UnitOfWorkFactoryContract,
)
from .manager import DatabaseManager
from .migrations import (
    FINGERPRINT_FORMAT,
    KNOWN_MIGRATIONS,
    LATEST_SCHEMA_VERSION,
    MAX_SUPPORTED_SCHEMA_VERSION,
    MIGRATION_V1_CHECKSUM,
    MIGRATION_V1_NAME,
    MIN_SUPPORTED_SCHEMA_VERSION,
    DatabaseMigrator,
    DatabaseSchemaError,
    SchemaStatus,
    logical_fingerprint,
    migration_manifest,
    verify_database,
)
from .repositories import AttendanceRepository
from .schema import SCHEMA_VERSION
from .unit_of_work import UnitOfWork, UnitOfWorkFactory

__all__ = [
    "AttendanceRecordDTO",
    "AttendanceRepository",
    "AttendanceRepositoryContract",
    "AttendanceUpdateDTO",
    "BackupDownload",
    "BackupProvider",
    "DatabaseCompatibilityError",
    "DatabaseManager",
    "DatabaseMigrator",
    "DatabaseSchemaError",
    "FINGERPRINT_FORMAT",
    "KNOWN_MIGRATIONS",
    "LATEST_SCHEMA_VERSION",
    "MAX_SUPPORTED_SCHEMA_VERSION",
    "MIGRATION_V1_CHECKSUM",
    "MIGRATION_V1_NAME",
    "MIN_SUPPORTED_SCHEMA_VERSION",
    "MemberDTO",
    "SCHEMA_VERSION",
    "SchemaStatus",
    "SyncOperationDTO",
    "SyncResultDTO",
    "TrainingSessionDTO",
    "UnitOfWork",
    "UnitOfWorkContract",
    "UnitOfWorkFactory",
    "UnitOfWorkFactoryContract",
    "logical_fingerprint",
    "migration_manifest",
    "verify_database",
]
