from __future__ import annotations

from .migrations import (
    DOMAIN_TABLES,
    EXPECTED_COLUMN_LAYOUTS,
    EXPECTED_FOREIGN_KEYS,
    EXPECTED_NAMED_INDEXES,
    EXPECTED_UNIQUE_CONSTRAINTS,
    LATEST_SCHEMA_VERSION,
    MAX_SUPPORTED_SCHEMA_VERSION,
    MIGRATION_TABLE_COLUMN_LAYOUT,
    MIGRATION_V1_CHECKSUM,
    MIGRATION_V1_NAME,
    MIN_SUPPORTED_SCHEMA_VERSION,
    REQUIRED_COLUMNS,
    REQUIRED_TABLE_SQL_FRAGMENTS,
    SCHEMA_V1_ADD_VERSION_SQL,
    SCHEMA_V1_CONDITIONAL_STEPS,
    SCHEMA_V1_STATEMENTS,
)


SCHEMA_VERSION = LATEST_SCHEMA_VERSION

__all__ = [
    "DOMAIN_TABLES",
    "EXPECTED_COLUMN_LAYOUTS",
    "EXPECTED_FOREIGN_KEYS",
    "EXPECTED_NAMED_INDEXES",
    "EXPECTED_UNIQUE_CONSTRAINTS",
    "LATEST_SCHEMA_VERSION",
    "MAX_SUPPORTED_SCHEMA_VERSION",
    "MIGRATION_TABLE_COLUMN_LAYOUT",
    "MIGRATION_V1_CHECKSUM",
    "MIGRATION_V1_NAME",
    "MIN_SUPPORTED_SCHEMA_VERSION",
    "REQUIRED_COLUMNS",
    "REQUIRED_TABLE_SQL_FRAGMENTS",
    "SCHEMA_VERSION",
    "SCHEMA_V1_ADD_VERSION_SQL",
    "SCHEMA_V1_CONDITIONAL_STEPS",
    "SCHEMA_V1_STATEMENTS",
]
